### ISSUE TITLE
Can hint text show the entire set of arguments?

### ISSUE THREAD

**Issue by tomleavy** [ray-x/lsp_signature.nvim#111]
I like having hint only mode vs the full window because it doesn't get in the way of reading the code above where I'm typing. The only issue I have with it is that it doesn't show the entire signature of the function, only the current argument. I there a way there can be a super compact mode like how hint works but still shows all the arguments?

**Comment by ray-x** [comment]
You can either set `floating_window` to false and use virtual text only mode
Also you can set `doc_lines=0` and `border='none'`  so the hint will be one line in height.

**Comment by mflova** [comment]
Similar to this issue, I would propose a mix between this mode and the current one. This mode would give you the current available options. For example, given a python function like this:

```python
def addition(num: int, num2: int = 2, num3: int = 3):
    return num + num2 + num3
```

I would like to see `num` as the first argument, and then, once the default argument zone is reached, the current mode only displays `num2`. However, since these are optional, it would be a good idea to display my available options (which in this case, they are `num2` and `num3`)

**Comment by ray-x** [comment]
@tomleavy 
You can use the api status_line() please check the README.md

**Comment by tomleavy** [comment]
Thanks, will give that a shot

**Comment by ray-x** [comment]
@mflova 
Seems that require LSP server supports. I tried pyright 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/1681295/178635482-5ddffc64-7d56-45ee-b7f1-c6c2c468f3b0.png">
The response does not show which parameter is optional.  It not a rival task for lsp-signature to identify the optional arguments.
