### ISSUE TITLE
Floating window is always a few lines above line that I am editing

### ISSUE THREAD

**Issue by jaapz** [ray-x/lsp_signature.nvim#23]
The hint is always a few lines above the line that I am editing:

![too high](https://user-images.githubusercontent.com/513050/120455992-80009f80-c395-11eb-9989-01d1e8c2d895.png)

**Comment by jaapz** [comment]
My config

![config123](https://user-images.githubusercontent.com/513050/120456174-a32b4f00-c395-11eb-977f-7a7e01a92a57.png)

**Comment by ray-x** [comment]
Ahh, someone does not like border.

Ok . It is an issue from upstream (neovim)
I will need time for this.

ATM, a workaround is set   {border = 'single',}
If you do not like the boarder color, set NormalFloat fg and bg to your current background color.

**Comment by argapost** [comment]
I have a similar issue. If I go to my init.lua and type: os.execute(
I get the following:
![image](https://user-images.githubusercontent.com/58076098/120636991-a3e3e400-c46e-11eb-82b5-1bf102ab937e.png)

the popup is a few lines above:

If I make a new empty file test.lua and type the same thing it works properly:

![image](https://user-images.githubusercontent.com/58076098/120637119-c675fd00-c46e-11eb-8113-a5df8f891df7.png)

My config:

```lua
	local settings = {
		bind = true, -- This is mandatory, otherwise border config won't get registered.
		-- If you want to hook lspsaga or other signature handler, pls set to false

		hint_enable = false, -- virtual hint enable
		-- hint_prefix = "! ",
		-- hint_scheme = "String",

		handler_opts = {
			border = 'single', -- double, single, shadow, none
		},

	}

  require('lsp_signature').on_attach(settings)
```

P.S.
The error col value outside rage has to be a separate issue because I get a similar thing with pyright and np.linspace where the arguments are not clearly defined in order lsp_signature to be able to locate them I guess (?)

**Comment by ray-x** [comment]
The issue @argapost  described had been fixed in upstream. You may need to upgrade your neovim and rebuild/install.
Alternatively
setting border to 

border = {
  {"╭", "NormalFloat"}, {"─", "NormalFloat"}, {"╮", "NormalFloat"}, {"│", "NormalFloat"},
  {"╯", "NormalFloat"}, {"─", "NormalFloat"}, {"╰", "NormalFloat"}, {"│", "NormalFloat"}
}

Can also fix issue you saw (I did not test).

**Comment by argapost** [comment]
I upgraded neovim and everything works now! Sorry, I should have known better!

thanks!

**Comment by jaapz** [comment]
Upgrading neovim fixed it for me, too. Sorry for the noise
