### ISSUE TITLE
Extra_trigger_chars don't seem to work

### ISSUE THREAD

**Issue by tsakirist** [ray-x/lsp_signature.nvim#44]
Hi,

I'm trying to trigger lsp-signature by the character '{' rather than '(' for invoking the constructor of a C++ class but it doesn't work, I get no signature pop-up when trying to use '{'.

I've added the character to the _extra_trigger_chars_ in the configuration like shown below:
 
```
-- Setup lsp-signature
require'lsp_signature'.on_attach({
  bind = true,
  doc_lines = 10,
  hint_enable = false,
  handler_opts = {
    border = "none", -- double, single, shadow, none
  },
  extra_trigger_chars = {"{"},
})
```
MRPE:
```
struct Example
{
    Example(int a, int b, std::string name)
        : m_a(a), m_b(b), m_name(std::move(name))
    {}

    int m_a, m_b;
    std::string m_name;
};

int main()
{
   Example ex{10, <-------- Here I do not get the floating window pop-up
}
```

**Comment by ray-x** [comment]
I think it maybe a issue from your lsp provider. Are you using ccls or clangd?

**Comment by tsakirist** [comment]
I am using mainly clangd but I just checked both clangd and ccls and in both cases no floating window pop-ups with the signature.

**Comment by ray-x** [comment]
My theory is  `ex{ ` was not treat by clangd as a valid constructor function and failed to send back the signature request.  
Extra trigger was a fix for those LSPs which failed to provide a correct trigger set. But if clangd failed to treat `ex` as a function, the extra trigger could not help with that.

**Comment by sam-mccall** [comment]
clangd developer here. That's correct, clangd today doesn't provide signature help for braced-initialization, and neither advertises nor supports `{` as a triggerCharacter.

**However** I'm currently implementing this feature, and even after exposing the `{` as a triggerCharacter and/or as an `extra_trigger_chars` in setup, this plugin **still* doesn't send a signaturehelp request unless `always_trigger` is specified.

This is easy to reproduce: set `extra_trigger_chars = {'{'}` and type `Foo{`, there'll be no request issued.

Also, even with `always_trigger`, things don't work quite right, given `bar(Foo{` it will request signature help for both calls but display the help for `bar` rather than `foo`.

@ray-x I think this is to do with the logic in `helper.lua` abound finding/fixing/improving trigger characters. I understand the desire to work around buggy servers, but it breaks correct servers. Maybe it could be opt-in?

(Please let me know I should open new issues instead).

**Comment by sam-mccall** [comment]
I confirmed locally that removing the ["search for the nearest trigger"](https://github.com/ray-x/lsp_signature.nvim/blob/be39dacc17d51531f9e3a50f88de0a45683c6634/lua/lsp_signature/helper.lua#L196-L223) block fixes both issues.

**Comment by ray-x** [comment]
@sam-mccall 
Thanks for the suggestion. I push a branch https://github.com/ray-x/lsp_signature.nvim/tree/extra_trigger
